---
# tasks file for ansible-role-eval_stig
- name: Include linux tasks for eval_stig role
  ansible.builtin.include_tasks: 
    file: linux.yml
    
    apply:
      tags:
      - configure
  tags:
    - configure
  when: ansible_os_family == "RedHat"

- name: Include windows tasks for eval_stig role
  ansible.builtin.include_tasks: 
    file: windows.yml
    
    apply:
      tags:
      - configure
  tags:
    - configure
  when: ansible_os_family == "Windows"
  
- name: Include checklist fetch tasks for eval_stig role
  ansible.builtin.include_tasks:
    file: checklist_fetch.yml
    apply:
      tags:
        - fetch
  tags:
    - fetch

- name: Push changes to git repository if any
  ansible.builtin.include_tasks:
    file: git_manage.yml
    apply:
      tags:
        - git
  tags:
    - git